# Generated by Django 3.2.19 on 2023-06-17 08:34

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимальное количество ингредиента: 1'), django.core.validators.MaxValueValidator(3000, message='Максимальное количество ингредиента: 3000')], verbose_name='Количество ингредиента'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимальное время приготовления в минутах: '), django.core.validators.MaxValueValidator(360, message='Максимальное время приготовления в минутах:')], verbose_name='Время в мин.'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, null=True, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['IGNORECASE'], message='Формат HEX: #______', regex='^#[A-Fa-f0-9]{3}([A-Fa-f0-9]{3})?$')], verbose_name='Цвет в формате HEX'),
        ),
    ]
